# Generated by Paige - Python build tool inspired by Sage
# To learn more, see .paige/paigefile.py

.DEFAULT_GOAL := default

cwd := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))
paige_dir := $(abspath $(cwd)/.paige)
paige_venv := $(paige_dir)/.venv
python := $(paige_venv)/bin/python
paige_executable := $(paige_dir)/generating_paigefile.py

# Setup Python environment
$(python):
	@echo 'Setting up Paige Python environment...'
	@cd $(paige_dir) && uv sync --active

.PHONY: paige
paige: $(python)
	@cd $(paige_dir) && $(python) paigefile.py

.PHONY: update-paige
update-paige: $(python)
	@cd $(paige_dir) && uv pip install --upgrade git+https://github.com/TheodorEmanuelsson/paige.git
	@cd $(paige_dir) && uv sync --active

.PHONY: clean-paige
clean-paige:
	@rm -rf $(paige_dir)/.venv
	@rm -rf $(paige_dir)/__pycache__

$(paige_executable):
	python -m paige.generate

.PHONY: default
default:
	python -m paige.cli run default

.PHONY: ruff-format
ruff-format:
	python -m paige.cli run ruff_format

.PHONY: ruff-fix
ruff-fix:
	python -m paige.cli run ruff_fix
