[project]
name = "dot_paige"
version = "0.1.0"
description = "A Python build tool inspired by Sage/Mage."
requires-python = ">=3.11"
dependencies = [
   "paige @ git+https://github.com/TheodorEmanuelsson/paige.git",
   "ruff>=0.12.0",
]
